# Site settings
title: Mind The Gap
header-img: img/home-bg.jpg
email: guillaume@viguierjust.com
description: "Thoughts about web consulting and bridging gaps in general"
baseurl: "/mindthegap"
url: "http://guillaumev.github.io"
twitter_username: SBootstrap
github_username:  guillaumev
facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
